### ISSUE TITLE
WeiboProvider使用的时候会出错，报一个Error: Undefined constant SHOPWWI_SOC_EMAIL

### ISSUE THREAD

**Issue by sparksisnotspark** [shopwwi/webman-socialite#1]
我看了这个常量在Constracts文件夹里的User.php里，我使用php8.0,与php7.2的版本里，测试了里面如果没有人为引入的这个User.php这个文件，会出错的，我不知道你们有没有测试这个WeiboProvider，同时，这种Constants的写法，是不是有问题，为什不使用一个Constants类包装起来，还是PHP8.1或更后的版本支持这种写法，

**Comment by phcent** [comment]
没有在低版本的php中测试过 会尽快处理
