### ISSUE TITLE
php8.2报错During inheritance of ArrayAccess

### ISSUE THREAD

**Issue by sherlock-7717** [shopwwi/webman-socialite#3]
PHP Fatal error:  During inheritance of ArrayAccess: Uncaught ErrorException: Return type of Shopwwi\WebmanSocialite\Config::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /www/wwwroot/****.com/vendor/shopwwi/webman-socialite/src/Config.php:68
Stack trace:
#0 /www/wwwroot/****.com/vendor/shopwwi/webman-socialite/src/Config.php(8): support\App::{closure}()
#1 /www/wwwroot/****.com/vendor/composer/ClassLoader.php(478): include('...')
#2 /www/wwwroot/****.com/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile()
#3 /www/wwwroot/****.com/vendor/shopwwi/webman-socialite/src/SocialiteManager.php(33): Composer\Autoload\ClassLoader->loadClass()
#4 /www/wwwroot/****.com/vendor/shopwwi/webman-socialite/src/Facade/Socialite.php(48): Shopwwi\WebmanSocialite\SocialiteManager->__construct()
#5 /www/wwwroot/****.com/vendor/shopwwi/webman-socialite/src/Facade/Socialite.php(60): Shopwwi\WebmanSocialite\Facade\Socialite::instance()
#6 /www/wwwroot/****.com/app/api/controller/QqController.php(20): Shopwwi\WebmanSocialite\Facade\Socialite::__callStatic()
#7 /www/wwwroot/****.com/vendor/workerman/webman-framework/src/App.php(349): app\api\controller\QqController->login()
#8 /www/wwwroot/****.com/vendor/webman/log/src/Middleware.php(58): Webman\App::Webman\{closure}()
#9 /www/wwwroot/****.com/vendor/workerman/webman-framework/src/App.php(341): Webman\Log\Middleware->process()
#10 /www/wwwroot/****.com/extend/middleware/ActionHook.php(29): Webman\App::Webman\{closure}()
#11 /www/wwwroot/****.com/vendor/workerman/webman-framework/src/App.php(341): middleware\ActionHook->process()
#12 /www/wwwroot/****.com/extend/middleware/BaseConfig.php(19): Webman\App::Webman\{closure}()
#13 /www/wwwroot/****.com/vendor/workerman/webman-framework/src/App.php(341): middleware\BaseConfig->process()
#14 /www/wwwroot/****.com/extend/middleware/AllowCrossDomain.php(12): Webman\App::Webman\{closure}()
#15 /www/wwwroot/****.com/vendor/workerman/webman-framework/src/App.php(341): middleware\AllowCrossDomain->process()
#16 /www/wwwroot/****.com/vendor/workerman/webman-framework/src/App.php(560): Webman\App::Webman\{closure}()
#17 /www/wwwroot/****.com/vendor/workerman/webman-framework/src/App.php(148): Webman\App::findRoute()
#18 /www/wwwroot/****.com/vendor/workerman/workerman/Connection/TcpConnection.php(646): Webman\App->onMessage()
#19 /www/wwwroot/****.com/vendor/workerman/workerman/Events/Select.php(311): Workerman\Connection\TcpConnection->baseRead()
#20 /www/wwwroot/****.com/vendor/workerman/workerman/Worker.php(1635): Workerman\Events\Select->loop()
#21 /www/wwwroot/****.com/vendor/workerman/workerman/Worker.php(1426): Workerman\Worker::forkOneWorkerForLinux()
#22 /www/wwwroot/****.com/vendor/workerman/workerman/Worker.php(1400): Workerman\Worker::forkWorkersForLinux()
#23 /www/wwwroot/****.com/vendor/workerman/workerman/Worker.php(560): Workerman\Worker::forkWorkers()
#24 /www/wwwroot/****.com/vendor/workerman/webman-framework/src/support/App.php(131): Workerman\Worker::runAll()
#25 /www/wwwroot/****.com/start.php(4): support\App::run()
#26 {main} in /www/wwwroot/****.com/vendor/shopwwi/webman-socialite/src/Config.php on line 8

Fatal error: During inheritance of ArrayAccess: Uncaught ErrorException: Return type of Shopwwi\WebmanSocialite\Config::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /www/wwwroot/****.com/vendor/shopwwi/webman-socialite/src/Config.php:68
Stack trace:
#0 /www/wwwroot/****.com/vendor/shopwwi/webman-socialite/src/Config.php(8): support\App::{closure}()
#1 /www/wwwroot/****.com/vendor/composer/ClassLoader.php(478): include('...')
#2 /www/wwwroot/****.com/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile()
#3 /www/wwwroot/****.com/vendor/shopwwi/webman-socialite/src/SocialiteManager.php(33): Composer\Autoload\ClassLoader->loadClass()
#4 /www/wwwroot/****.com/vendor/shopwwi/webman-socialite/src/Facade/Socialite.php(48): Shopwwi\WebmanSocialite\SocialiteManager->__construct()
#5 /www/wwwroot/****.com/vendor/shopwwi/webman-socialite/src/Facade/Socialite.php(60): Shopwwi\WebmanSocialite\Facade\Socialite::instance()
#6 /www/wwwroot/****.com/app/api/controller/QqController.php(20): Shopwwi\WebmanSocialite\Facade\Socialite::__callStatic()
#7 /www/wwwroot/****.com/vendor/workerman/webman-framework/src/App.php(349): app\api\controller\QqController->login()
#8 /www/wwwroot/****.com/vendor/webman/log/src/Middleware.php(58): Webman\App::Webman\{closure}()
#9 /www/wwwroot/****.com/vendor/workerman/webman-framework/src/App.php(341): Webman\Log\Middleware->process()
#10 /www/wwwroot/****.com/extend/middleware/ActionHook.php(29): Webman\App::Webman\{closure}()
#11 /www/wwwroot/****.com/vendor/workerman/webman-framework/src/App.php(341): middleware\ActionHook->process()
#12 /www/wwwroot/****.com/extend/middleware/BaseConfig.php(19): Webman\App::Webman\{closure}()
#13 /www/wwwroot/****.com/vendor/workerman/webman-framework/src/App.php(341): middleware\BaseConfig->process()
#14 /www/wwwroot/****.com/extend/middleware/AllowCrossDomain.php(12): Webman\App::Webman\{closure}()
#15 /www/wwwroot/****.com/vendor/workerman/webman-framework/src/App.php(341): middleware\AllowCrossDomain->process()
#16 /www/wwwroot/****.com/vendor/workerman/webman-framework/src/App.php(560): Webman\App::Webman\{closure}()
#17 /www/wwwroot/****.com/vendor/workerman/webman-framework/src/App.php(148): Webman\App::findRoute()
#18 /www/wwwroot/****.com/vendor/workerman/workerman/Connection/TcpConnection.php(646): Webman\App->onMessage()
#19 /www/wwwroot/****.com/vendor/workerman/workerman/Events/Select.php(311): Workerman\Connection\TcpConnection->baseRead()
#20 /www/wwwroot/****.com/vendor/workerman/workerman/Worker.php(1635): Workerman\Events\Select->loop()
#21 /www/wwwroot/****.com/vendor/workerman/workerman/Worker.php(1426): Workerman\Worker::forkOneWorkerForLinux()
#22 /www/wwwroot/****.com/vendor/workerman/workerman/Worker.php(1400): Workerman\Worker::forkWorkersForLinux()
#23 /www/wwwroot/****.com/vendor/workerman/workerman/Worker.php(560): Workerman\Worker::forkWorkers()
#24 /www/wwwroot/****.com/vendor/workerman/webman-framework/src/support/App.php(131): Workerman\Worker::runAll()
#25 /www/wwwroot/****.com/start.php(4): support\App::run()
#26 {main} in /www/wwwroot/****.com/vendor/shopwwi/webman-socialite/src/Config.php on line 8
Worker[17607] process terminated with ERROR: E_ERROR "During inheritance of ArrayAccess: Uncaught ErrorException: Return type of Shopwwi\WebmanSocialite\Config::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /www/wwwroot/****.com/vendor/shopwwi/webman-socialite/src/Config.php:68
Stack trace:
#0 /www/wwwroot/****.com/vendor/shopwwi/webman-socialite/src/Config.php(8): support\App::{closure}()
#1 /www/wwwroot/****.com/vendor/composer/ClassLoader.php(478): include('...')
#2 /www/wwwroot/****.com/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile()
#3 /www/wwwroot/****.com/vendor/shopwwi/webman-socialite/src/SocialiteManager.php(33): Composer\Autoload\ClassLoader->loadClass()
#4 /www/wwwroot/****.com/vendor/shopwwi/webman-socialite/src/Facade/Socialite.php(48): Shopwwi\WebmanSocialite\SocialiteManager->__construct()
#5 /www/wwwroot/****.com/vendor/shopwwi/webman-socialite/src/Facade/Socialite.php(60): Shopwwi\WebmanSocialite\Facade\Socialite::instance()
#6 /www/wwwroot/****.com/app/api/controller/QqController.php(20): Shopwwi\WebmanSocialite\Facade\Socialite::__callStatic()
#7 /www/wwwroot/****.com/vendor/workerman/webman-framework/src/App.php(349): app\api\controller\QqController->login()
#8 /www/wwwroot/****.com/vendor/webman/log/src/Middleware.php(58): Webman\App::Webman\{closure}()
#9 /www/wwwroot/****.com/vendor/workerman/webman-framework/src/App.php(341): Webman\Log\Middleware->process()
#10 /www/wwwroot/****.com/extend/middleware/ActionHook.php(29): Webman\App::Webman\{closure}()
#11 /www/wwwroot/****.com/vendor/workerman/webman-framework/src/App.php(341): middleware\ActionHook->process()
#12 /www/wwwroot/****.com/extend/middleware/BaseConfig.php(19): Webman\App::Webman\{closure}()
#13 /www/wwwroot/****.com/vendor/workerman/webman-framework/src/App.php(341): middleware\BaseConfig->process()
#14 /www/wwwroot/****.com/extend/middleware/AllowCrossDomain.php(12): Webman\App::Webman\{closure}()
#15 /www/wwwroot/****.com/vendor/workerman/webman-framework/src/App.php(341): middleware\AllowCrossDomain->process()
#16 /www/wwwroot/****.com/vendor/workerman/webman-framework/src/App.php(560): Webman\App::Webman\{closure}()
#17 /www/wwwroot/****.com/vendor/workerman/webman-framework/src/App.php(148): Webman\App::findRoute()
#18 /www/wwwroot/****.com/vendor/workerman/workerman/Connection/TcpConnection.php(646): Webman\App->onMessage()
#19 /www/wwwroot/****.com/vendor/workerman/workerman/Events/Select.php(311): Workerman\Connection\TcpConnection->baseRead()
#20 /www/wwwroot/****.com/vendor/workerman/workerman/Worker.php(1635): Workerman\Events\Select->loop()
#21 /www/wwwroot/****.com/vendor/workerman/workerman/Worker.php(1426): Workerman\Worker::forkOneWorkerForLinux()
#22 /www/wwwroot/****.com/vendor/workerman/workerman/Worker.php(1400): Workerman\Worker::forkWorkersForLinux()
#23 /www/wwwroot/****.com/vendor/workerman/workerman/Worker.php(560): Workerman\Worker::forkWorkers()
#24 /www/wwwroot/****.com/vendor/workerman/webman-framework/src/support/App.php(131): Workerman\Worker::runAll()
#25 /www/wwwroot/****.com/start.php(4): support\App::run()
#26 {main} in /www/wwwroot/****.com/vendor/shopwwi/webman-socialite/src/Config.php on line 8"
worker[webman:17607] exit with status 65280

使用方式：
$qqUser = Socialite::driver('qq')->userFromCode($code);

**Comment by phcent** [comment]
已修复
